export const colors = {
  background:          '#FAF8F5',
  surface:             '#F0EDE8',
  border:              '#E5E0D8',
  text:                '#1C1B1A',
  textSecondary:       '#9A9590',
  userBubble:          '#1C1B1A',
  userBubbleText:      '#FFFFFF',
  assistantBubble:     '#ECEAE5',
  assistantBubbleText: '#1C1B1A',
  accent:              '#1C1B1A',
  accentDisabled:      '#C8C4BC',
  danger:              '#C0392B',
  warning:             '#FFF3CD',
  warningBorder:       '#FFE08A',
  warningText:         '#7A5C00',
  // Lavender / purple brand tokens
  lavender:            '#F5F3FF',
  lavenderSurface:     '#EDE9FE',
  purple:              '#7C3AED',
  purpleLight:         '#8B5CF6',
  purpleDim:           '#A78BFA',
  navy:                '#1E1B4B',
  waveA:               '#7C3AED',
  waveB:               '#EC4899',
  waveC:               '#06B6D4',
};
