import Config from 'react-native-config';

type AppEnv = 'dev' | 'qa' | 'prod';

/**
 * Resolve APP_ENV from react-native-config.
 *
 * react-native-config injects values via Android BuildConfig (generated by
 * dotenv.gradle). This only runs when Gradle bundles the variant — in
 * debuggableVariants (metro-connected debug builds) the injection may not
 * fire. Fall back to 'dev' so the app never crashes due to a missing env
 * value in a development or test build.
 */
function resolveEnv(): AppEnv {
  const value = Config.APP_ENV;
  if (value === 'dev' || value === 'qa' || value === 'prod') {
    return value;
  }
  // Fallback: dotenv.gradle didn't fire (e.g. debuggable Metro builds).
  // Default to 'dev' so the app stays usable during development.
  if (__DEV__) {
    return 'dev';
  }
  throw new Error(`Invalid APP_ENV value: "${value ?? 'undefined'}". Must be dev, qa, or prod.`);
}

function resolveString(value: string | undefined, name: string, fallback?: string): string {
  if (value) {
    return value;
  }
  if (fallback !== undefined) {
    return fallback;
  }
  if (__DEV__) {
    // Don't crash in dev — log and return a placeholder so screens still render.
    console.warn(`[env] Missing required env variable: ${name}`);
    return '';
  }
  throw new Error(`Missing required env variable: ${name}`);
}

export const ENV: AppEnv = resolveEnv();

export const AppConfig = {
  env: ENV,
  isDev: ENV === 'dev',
  isQA: ENV === 'qa',
  isProd: ENV === 'prod',
  displayName: resolveString(Config.APP_DISPLAY_NAME, 'APP_DISPLAY_NAME', 'Olix'),
  bundleId: resolveString(Config.BUNDLE_ID, 'BUNDLE_ID', 'com.olix.dev'),
  modelCdnUrl: resolveString(
    Config.MODEL_CDN_URL,
    'MODEL_CDN_URL',
    'https://dev-cdn.example.com/models',
  ),
  sentryDsn: Config.SENTRY_DSN ?? '',
} as const;
